console:
    verbose: True # Bool value to decide if console prints output during execution

sampling: # Sampling behaviour: parameters for filtering noise in the signal
    minSamples: 6 # Minimum samples taken per point 
    maxSamples: 30 # Maximum samples that can be taken if signal is noisy enough
    vClearance: 0.7 # Height of vertical margins, in units of Vpp/100
    periods: 3 # Minimum periods taken into consideration for measurements
    maxTries: 3 # Maximum number of times an irregular point is measured again before being ignored

autostep:
    ratioTolerance: 0.5
    minStep: 5
    maxStep: 300
    minCountSinceFail: 3
    stepFactor: 1.5

interpolation:
    secDerivWeight: 0.8
    closeness: 0.3
    initialSamples: 5